name: Single Workflow

on:
  workflow_dispatch:

env:
  name: Hasnain

jobs:
  Variable_Declaration:
    runs-on: ubuntu-latest
    env:
      age: 18
    steps:
      - name: Step One
        run: echo "$name is $age years old and study in class $class."
        env:
          class: 18
